apiVersion: v1
kind: LimitRange
metadata:
  name: payments-container-defaults
  namespace: payments
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 128Mi
    max:
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 10m
      memory: 32Mi
