apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payments-developer
  namespace: payments
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-dev
  namespace: payments
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
- kind: User
  name: payments-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: payments-developer
  apiGroup: rbac.authorization.k8s.io
